package cmd

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/plexusone/agent-code-review/pkg/aireview"
	"github.com/plexusone/agent-code-review/pkg/config"
	"github.com/plexusone/agent-code-review/pkg/input"
	"github.com/plexusone/agent-code-review/pkg/review"
	"github.com/spf13/cobra"
)

var aiReviewCmd = &cobra.Command{
	Use:   "ai-review <pr-number>",
	Short: "Generate and post an AI-powered code review",
	Long: `Generate an AI-powered code review for a GitHub pull request using LLMs.

The review is generated by analyzing the PR diff with a large language model,
then posted to GitHub as a review comment.

Supported models include Claude, GPT, Gemini, Grok, and Ollama (local).

Example:
  acr ai-review 123 -o owner -r repo
  acr ai-review 123 -o owner -r repo --model gpt-4o --scope security
  acr ai-review 123 -o owner -r repo --dry-run`,
	Args: cobra.ExactArgs(1),
	RunE: runAIReview,
}

func init() {
	rootCmd.AddCommand(aiReviewCmd)

	// Model selection
	aiReviewCmd.Flags().String("model", "", "LLM model to use (default: claude-sonnet-4, env: OMNILLM_MODEL)")

	// Review scope
	aiReviewCmd.Flags().String("scope", "", "Review focus: full, security, style, performance (default: full, env: ACR_REVIEW_SCOPE)")

	// Review event
	aiReviewCmd.Flags().StringP("event", "e", "", "Review event: APPROVE, REQUEST_CHANGES, COMMENT (default: from AI verdict, env: ACR_REVIEW_EVENT)")

	// Dry run
	aiReviewCmd.Flags().Bool("dry-run", false, "Print review without posting to GitHub")

	// Max tokens
	aiReviewCmd.Flags().Int("max-tokens", 4096, "Maximum response tokens")
}

func runAIReview(cmd *cobra.Command, args []string) error {
	ctx := context.Background()

	// Parse repository config
	repoCfg, err := getRepoConfig(cmd)
	if err != nil {
		return err
	}

	// Parse PR number
	prNumber, err := input.ParsePRNumber(args[0])
	if err != nil {
		return err
	}

	// Get model (flag > env > default)
	model, _ := cmd.Flags().GetString("model")
	if model == "" {
		model = aireview.GetModelFromEnv()
	}

	// Get scope (flag > env > default)
	scopeStr, _ := cmd.Flags().GetString("scope")
	var scope aireview.Scope
	if scopeStr != "" {
		if !aireview.IsValidScope(scopeStr) {
			return fmt.Errorf("invalid scope: %s (must be one of: full, security, style, performance)", scopeStr)
		}
		scope = aireview.Scope(scopeStr)
	} else {
		scope = aireview.GetScopeFromEnv()
	}

	// Get other flags
	dryRun, _ := cmd.Flags().GetBool("dry-run")
	maxTokens, _ := cmd.Flags().GetInt("max-tokens")
	eventOverride, _ := cmd.Flags().GetString("event")

	// Validate event override if provided
	if eventOverride != "" {
		eventOverride = strings.ToUpper(eventOverride)
		if err := input.ValidateReviewEvent(eventOverride); err != nil {
			return err
		}
	}

	// Create GitHub client
	ghClient, err := config.CreateClient(ctx)
	if err != nil {
		return err
	}

	// Fetch PR info
	fmt.Printf("Fetching PR #%d from %s/%s...\n", prNumber, repoCfg.Owner, repoCfg.Repo)
	pr, err := ghClient.GetPR(ctx, repoCfg.Owner, repoCfg.Repo, prNumber)
	if err != nil {
		return fmt.Errorf("fetching PR: %w", err)
	}

	// Fetch diff
	fmt.Println("Fetching diff...")
	diff, err := ghClient.GetPRDiff(ctx, repoCfg.Owner, repoCfg.Repo, prNumber)
	if err != nil {
		return fmt.Errorf("fetching diff: %w", err)
	}

	// Create AI reviewer
	fmt.Printf("Generating %s review with %s...\n", scope, model)
	reviewer, err := aireview.NewReviewer(aireview.Config{
		Model:     model,
		Scope:     scope,
		MaxTokens: maxTokens,
	})
	if err != nil {
		return fmt.Errorf("creating reviewer: %w", err)
	}
	defer reviewer.Close()

	// Generate review
	reviewOutput, err := reviewer.Review(ctx, aireview.ReviewInput{
		Title: pr.Title,
		Body:  pr.Body,
		Diff:  diff,
	})
	if err != nil {
		return fmt.Errorf("generating review: %w", err)
	}

	fmt.Printf("Review generated (%d tokens used)\n", reviewOutput.TokensUsed)

	// Determine event
	event := reviewOutput.Verdict
	if eventOverride != "" {
		event = eventOverride
	}
	// Default to COMMENT from env if set
	if envEvent := os.Getenv("ACR_REVIEW_EVENT"); envEvent != "" && eventOverride == "" {
		envEvent = strings.ToUpper(envEvent)
		if input.ValidateReviewEvent(envEvent) == nil {
			event = envEvent
		}
	}

	// Dry run: just print
	if dryRun {
		fmt.Println("\n--- Review (dry run) ---")
		fmt.Printf("Event: %s\n\n", event)
		fmt.Println(reviewOutput.Content)
		return nil
	}

	// Post review to GitHub
	fmt.Printf("Posting review with event: %s...\n", event)
	result, err := ghClient.CreateReview(ctx, &review.ReviewInput{
		Owner:    repoCfg.Owner,
		Repo:     repoCfg.Repo,
		PRNumber: prNumber,
		Event:    review.ReviewEvent(event),
		Body:     reviewOutput.Content,
	})
	if err != nil {
		return fmt.Errorf("posting review: %w", err)
	}

	fmt.Printf("Review posted: %s\n", result.HTMLURL)
	return nil
}
